approval_policy = "never"

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=jwchmioeiiccjfruyvmc&features=branching%2Caccount%2Cdocs%2Cdebugging%2Cdevelopment%2Cfunctions%2Cdatabase%2Cstorage"
